services:
  browser-mcp:
    build:
      context: .
      dockerfile: mcp_server/browser/Dockerfile
    ports:
      - ${BROWSER_MCP_PORT}:8000
    shm_size: "2gb"
    deploy:
      resources:
        limits:
          memory: 4G
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - MODEL_NAME=${MODEL_NAME}
      - DISPLAY=:0
